### ISSUE TITLE
UX bug in saved files menu

### ISSUE THREAD

**Issue by orchid-hybrid** [tca/veneer#2]
Temporary work disappears when switching between between saved files, without saving.

To reproduce:
- Create two custom saved files.
- Add some text in one of them
- Switch to the other, then switch back
- All the work is gone

You can save before switching between files, but it would be better if temporary work wasn't erased too.

**Comment by tca** [comment]
fixed b39f89c3a72acc4681935a114e3d5d9f66053888

**Comment by orchid-hybrid** [comment]
Thanks tca!
